{{- if and .Values.expose.traefik.enabled (eq .Values.expose.type "traefik") .Values.expose.traefik.httpsRedirect.enabled }}
---
apiVersion: {{ .Values.expose.traefik.apiVersion }}
kind: Middleware
metadata:
  name: {{ include "harbor.fullname" . }}-https-redirect
  namespace: {{ .Release.Namespace  | quote  }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}

{{- if and .Values.expose.traefik.enabled (eq .Values.expose.type "traefik") .Values.expose.traefik.ipWhitelist.enabled }}
---
apiVersion: {{ .Values.expose.traefik.apiVersion }}
kind: Middleware
metadata:
  name: {{ include "harbor.fullname" . }}-ip-whitelist
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  ipWhiteList:
    sourceRange:
      {{- range .Values.expose.traefik.ipWhitelist.sourceRange }}
      - {{ . }}
      {{- end }}
{{- end }}
