# Default values for reliza-cd.
# This is a YAML-formatted file.

mode: STANDALONE # options: STANDALONE, EXISTING_ARGO, NEW_ARGO
imagePullPolicy: IfNotPresent
images:
  relizacdImage: relizaio/reliza-cd:26.02.2@sha256:2e3803feacb0bc738fd26793e941f0391f0451b83eb536e3938c168265486544

enableWatcher: true
backup:
  enabled: false
  schedule: "0 2 * * *" # cron schedule for backup, default is 2 AM daily
  awsRegion: "ca-central-1"
  prefix: "reliza-cd-backup"

storageSize: 1G

create_secret_in_chart: none # regular, none
hubUri: https://app.relizahub.com
relizaApiId: placeholder # instance api id
relizaApiKey: placeholder # instance api key
argoHelmVersion: 6.6.0
